labels:
  'bugFix':
    - '\bbugFix[s]?\b'
  'crashFix':
    - '\bcrashFix\b'
  'hotFix':
    - '\hotFix\b'
    - '\bdupe\b'
  'feature':
    - '\bfeature\b'
  'enhancement':
    - '\benhancement\b'
  'documentation':
    - '\bdocumentation\b'
