labels:
  'bugFix':
    - '\bbugFix[s]?\b'
  'crashFix':
    - '\bcrash( Fix)?\b'
  'hotFix':
    - '\bhotFix\b'
  'feature':
    - '\bfeature\b'
  'enhancement':
    - '\benhancement\b'
  'documentation':
    - '\bdocumentation\b'
