name: PR Labeler
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pr-labeler.yml # optional, .github/pr-labeler.yml is the default value
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: jinmayamashita/ready-for-review@1.0.0
        with:
         in-progress-label: 'work in progress'
         ready-for-review-label: 'Ready For Review'
         repo-token: ${{ secrets.GITHUB_TOKEN }}
