on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  foo:
    runs-on: ubuntu-latest
    name: fooName
    steps:
    - name: label swapping
      uses: jinmayamashita/ready-for-review@1.0.0
      with:
        in-progress-label: 'work in progress'
        ready-for-review-label: 'ready for review'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
