name: Your-Labeler-name 
on: 
  pull_request:
    types: [review_requested, ready_for_review]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
