name: Assign auto label
on: [pull_request]
jobs:
  working_label:
    runs-on: ubuntu-latest
    
    steps:
    
     - name: action labler
       if: github.event.pull_request.draft == false
       uses: actions/labeler@v2
       with:
        configuration-path: .github/labelers.yml
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        
     - name: Label working progress
       if: github.event.pull_request.draft == true
       uses: AlbertHernandez/working-label-action@v1.0.3
       with:
        work_in_progress_label: 'Work in progress'
        ready_to_review_label: 'Ready to review'
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
     - name: Check Labels
       id: labeler
       uses: jimschubert/labeler-action@v2
       with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

