name: Assign work in progress label when pull request is updated
on: [pull_request]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Synchronize labels
        uses: julb/action-manage-label@v1
        with:
          from: https://github.com/RahulPere/LabelSet/blob/master/Labeler.yml
          skip_delete: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          
   
